name: C++ CI Ubuntu build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt-get install clang-8 libc++-8-dev libc++abi-8-dev -y
          mkdir deps_dir
          DEPS_DIR="$PWD/deps_dir"
          cd ${DEPS_DIR}
          CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.3-Linux-x86_64.tar.gz"
          mkdir cmake && wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=${DEPS_DIR}/cmake/bin:${PATH}
          cd -
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 ../
