name: C++ CI Ubuntu build clang-8 Debug

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install clang-8 libc++-8-dev libc++abi-8-dev gcc-8 g++-8 -y
          mkdir deps_dir
          DEPS_DIR="$PWD/deps_dir"
          cd ${DEPS_DIR}
          CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.3-Linux-x86_64.tar.gz"
          mkdir cmake && wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=${DEPS_DIR}/cmake/bin:${PATH}
          cd -
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/clang -DANTARA_BUILD_EXAMPLES=ON -DUSE_LUA_ANTARA_WRAPPER=ON -DANTARA_BUILD_UNIT_TESTS=ON ../
    
    - name: make
      run: |
          cd build
          cmake --build . --config Debug
    
    - name: tests
      run: |
          cd build/bin/unit_tests
          for i in *_tests; do ./${i} --reporters=xml --out=${i}-result.xml -s || true; done;
   
    - name: upload tests
      run: |
          cd build/bin/unit_tests
          curl https://report.ci/upload.py --output upload.py && python upload.py -n "Doctest [github-actions ubuntu-latest-clang8-debug]" --merge ".*"
