name: C++ CI build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          #! CMake
          mkdir deps_dir && cd deps_dir
          CMAKE_URL="https://cmake.org/files/v3.15/cmake-3.15.0-Linux-x86_64.tar.gz"
          mkdir -p cmake
          wget ${CMAKE_URL}
          echo "Listing directories"
          ls -R .
          tar -xvf cmake-3.15.0-Linux-x86_64.tar.gz -C cmake
          export PATH="${PWD}/cmake/bin:${PATH}"
          cmake -v
          cd -

          #! dependencies
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install clang-8 libc++-8-dev libc++abi-8-dev gcc-8 g++-8 -y

      - name: prepare build folder
        env:
          ANTARA_CMAKE_BUILD_TYPE: ${{matrix.build_type}}
        run: |
          cmake -v
          mkdir cmake-build-${ANTARA_CMAKE_BUILD_TYPE} && cd cmake-build-${ANTARA_CMAKE_BUILD_TYPE}
          cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=${ANTARA_CMAKE_BUILD_TYPE} -DCMAKE_C_COMPILER=/usr/bin/clang-8 -DANTARA_BUILD_EXAMPLES=ON -DUSE_LUA_ANTARA_WRAPPER=ON -DANTARA_BUILD_UNIT_TESTS=ON ../

      - name: build
        env:
          ANTARA_CMAKE_BUILD_TYPE: ${{matrix.build_type}}
          PATH: "deps_dir/cmake/bin:${PATH}"
        working-directory: cmake-build-${{matrix.build_type}}
        run: |
          cmake --build . --config ${ANTARA_CMAKE_BUILD_TYPE}


      - name: run unit tests
        working-directory: cmake-build-${{matrix.build_type}}/bin/unit_tests
        run: |
          for i in *_tests; do ./${i} --reporters=xml --out=${i}-result.xml -s || true; done;


      - name: upload unit tests
        working-directory: cmake-build-${{matrix.build_type}}/bin/unit_tests
        env:
          REPORT_CI_TOKEN: ${{ secrets.REPORT_CI_TOKEN }}
          ANTARA_CMAKE_BUILD_TYPE: ${{matrix.build_type}}
        run: |
          curl https://report.ci/upload.py --output upload.py && python upload.py --include='*.xml' --sha $GITHUB_SHA -n "Doctest [github-actions ubuntu-latest-clang8-{ANTARA_CMAKE_BUILD_TYPE}]" --merge ".*"


